name: Testing the action

on:
  push:
    branches:
      - '*'

jobs:
  comments_to_asana:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: 'Echoing the job'
        run: echo "Pushing comments to Asana"
      - name: 'Pushing the comments'
        uses: ./
        id: 'CommentPush'

