name: Testing the action

on:
  push:
    branches:
      - '*'

jobs:
  comments_to_asana:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: 'Pushing the comments'
        uses: ./
        id: 'CommentPush'
        env:
          ASANA_PAT: ${{ secrets.ASANA_PAT }}

